<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.MongoDB.Driver.v3" Version="9.5.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CarRentalService.Aspire\CarRentalService.Aspire.ServiceDefaults\CarRentalService.Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\CarRentalService.Core.Contracts\CarRentalService.Core.Contracts.csproj" />
    <ProjectReference Include="..\CarRentalService.Infrastructure.Nats\CarRentalService.Infrastructure.Nats.csproj" />
    <ProjectReference Include="..\CarRentalService.Infrastructure\CarRentalService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
