<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>4073bf33-20b5-4ce1-acbe-18c320ffafea</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.1" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="9.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CarRentalService.WebApplication\CarRentalService.WebApplication.csproj" />
  </ItemGroup>

</Project>
